In [30]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer   #to convert words in the document or sentence to numbers 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB

In [31]:
df = pd.read_csv(r'G:\Machine Learning\jupyter csv files\spam_email.csv')
df.head(3)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [32]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [33]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head(3)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1

In [34]:
df = df.drop(['Category'],axis='columns')
df.head(3)

Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1

In [35]:
cv = CountVectorizer()
cv

CountVectorizer()

In [36]:
y = df.spam
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: spam, Length: 5572, dtype: int64

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df.Message,y,test_size=0.3)

In [38]:
X = cv.fit_transform(X_train.values)
X

<3900x7256 sparse matrix of type '<class 'numpy.int64'>'
	with 52167 stored elements in Compressed Sparse Row format>

In [39]:
X.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
gnb  =GaussianNB()   
mnb = MultinomialNB()
bnb= BernoulliNB()

In [41]:
mnb.fit(X,y_train)


MultinomialNB()

In [42]:
bnb.fit(X,y_train)

BernoulliNB()

In [43]:
gnb.fit(X,y_train)   #throws error 

TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.

In [44]:
emails1 =[
'Hey mohan, can we get together to watch football game tomorrow?'
]
email1 = cv.transform(emails1)

In [45]:
emails2 =[
'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
email2 = cv.transform(emails2)

In [46]:
bnb.predict(email1)

array([0], dtype=int64)

In [47]:
mnb.predict(email1)

array([0], dtype=int64)

In [48]:
bnb.predict(email2)

array([0], dtype=int64)

In [49]:
mnb.predict(email2)

array([1], dtype=int64)

In [50]:
Xc = cv.transform(X_test.values)

In [51]:
mnb.score(Xc,y_test)

0.986244019138756

In [52]:
bnb.score(Xc,y_test)

0.9826555023923444