In [1]:
import pandas as pd
from sklearn.datasets import load_wine
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

In [2]:
wine = load_wine()

In [3]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [4]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
df = pd.DataFrame(wine.data,wine.target,columns = wine.feature_names)
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
0    13.20        1.78  2.14               11.2      100.0           2.65   
0    13.16        2.36  2.67               18.6      101.0           2.80   
0    14.37        1.95  2.50               16.8      113.0           3.85   
0    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
0        2.76                  0.26             1.28             4.38  1.05   
0        3.24                  0.30             2.81             5.68  1.03   
0        3.49                  0.24             2.18             7.80  0.86   
0        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
0                          3.40   1050.0  
0                          3.17   1185.0  
0                          3.45   1480.0  
0                          2.93    735.0

In [6]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [7]:
df['target'] = wine.target
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
0    13.20        1.78  2.14               11.2      100.0           2.65   
0    13.16        2.36  2.67               18.6      101.0           2.80   
0    14.37        1.95  2.50               16.8      113.0           3.85   
0    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
0        2.76                  0.26             1.28             4.38  1.05   
0        3.24                  0.30             2.81             5.68  1.03   
0        3.49                  0.24             2.18             7.80  0.86   
0        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
0                          3.40   1050.0       0  
0                          3.17   1185.0       0  
0                          3.45   1480.0       0  
0                          2.93    735.0       0

In [8]:
df['wine_class'] = df.target.apply(lambda x :wine.target_names[x])
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0     14.23        1.71  2.43               15.6      127.0           2.80   
0     13.20        1.78  2.14               11.2      100.0           2.65   
0     13.16        2.36  2.67               18.6      101.0           2.80   
0     14.37        1.95  2.50               16.8      113.0           3.85   
0     13.24        2.59  2.87               21.0      118.0           2.80   
..      ...         ...   ...                ...        ...            ...   
2     13.71        5.65  2.45               20.5       95.0           1.68   
2     13.40        3.91  2.48               23.0      102.0           1.80   
2     13.27        4.28  2.26               20.0      120.0           1.59   
2     13.17        2.59  2.37               20.0      120.0           1.65   
2     14.13        4.10  2.74               24.5       96.0           2.05   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0         3.06                  0.28             2.29             5.64  1.04   
0         2.76                  0.26             1.28             4.38  1.05   
0         3.24                  0.30             2.81             5.68  1.03   
0         3.49                  0.24             2.18             7.80  0.86   
0         2.69                  0.39             1.82             4.32  1.04   
..         ...                   ...              ...              ...   ...   
2         0.61                  0.52             1.06             7.70  0.64   
2         0.75                  0.43             1.41             7.30  0.70   
2         0.69                  0.43             1.35            10.20  0.59   
2         0.68                  0.53             1.46             9.30  0.60   
2         0.76                  0.56             1.35             9.20  0.61   

    od280/od315_of_diluted_wines  proline  target wine_class  
0                           3.92   1065.0       0    class_0  
0                           3.40   1050.0       0    class_0  
0                           3.17   1185.0       0    class_0  
0                           3.45   1480.0       0    class_0  
0                           2.93    735.0       0    class_0  
..                           ...      ...     ...        ...  
2                           1.74    740.0       2    class_2  
2                           1.56    750.0       2    class_2  
2                           1.56    835.0       2    class_2  
2                           1.62    840.0       2    class_2  
2                           1.60    560.0       2    class_2  

[178 rows x 15 columns]

In [9]:
a = df[df.target==1]   #to view from where the target column gives 1 
len(a)

71

In [10]:
b = df[df.target==0]   #to view from where the target column gives 0
len(b)

59

In [11]:
c = df[df.target==2]   #to view from where the target column gives 2 
len(c)

48

In [12]:
len(df)

178

In [13]:
a.mean()

alcohol                          12.278732
malic_acid                        1.932676
ash                               2.244789
alcalinity_of_ash                20.238028
magnesium                        94.549296
total_phenols                     2.258873
flavanoids                        2.080845
nonflavanoid_phenols              0.363662
proanthocyanins                   1.630282
color_intensity                   3.086620
hue                               1.056282
od280/od315_of_diluted_wines      2.785352
proline                         519.507042
target                            1.000000
dtype: float64

In [14]:
b.mean()

alcohol                           13.744746
malic_acid                         2.010678
ash                                2.455593
alcalinity_of_ash                 17.037288
magnesium                        106.338983
total_phenols                      2.840169
flavanoids                         2.982373
nonflavanoid_phenols               0.290000
proanthocyanins                    1.899322
color_intensity                    5.528305
hue                                1.062034
od280/od315_of_diluted_wines       3.157797
proline                         1115.711864
target                             0.000000
dtype: float64

In [15]:
c.mean()

alcohol                          13.153750
malic_acid                        3.333750
ash                               2.437083
alcalinity_of_ash                21.416667
magnesium                        99.312500
total_phenols                     1.678750
flavanoids                        0.781458
nonflavanoid_phenols              0.447500
proanthocyanins                   1.153542
color_intensity                   7.396250
hue                               0.682708
od280/od315_of_diluted_wines      1.683542
proline                         629.895833
target                            2.000000
dtype: float64

In [16]:
X = df.drop(['target','wine_class'],axis = 'columns')
X

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0     14.23        1.71  2.43               15.6      127.0           2.80   
0     13.20        1.78  2.14               11.2      100.0           2.65   
0     13.16        2.36  2.67               18.6      101.0           2.80   
0     14.37        1.95  2.50               16.8      113.0           3.85   
0     13.24        2.59  2.87               21.0      118.0           2.80   
..      ...         ...   ...                ...        ...            ...   
2     13.71        5.65  2.45               20.5       95.0           1.68   
2     13.40        3.91  2.48               23.0      102.0           1.80   
2     13.27        4.28  2.26               20.0      120.0           1.59   
2     13.17        2.59  2.37               20.0      120.0           1.65   
2     14.13        4.10  2.74               24.5       96.0           2.05   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0         3.06                  0.28             2.29             5.64  1.04   
0         2.76                  0.26             1.28             4.38  1.05   
0         3.24                  0.30             2.81             5.68  1.03   
0         3.49                  0.24             2.18             7.80  0.86   
0         2.69                  0.39             1.82             4.32  1.04   
..         ...                   ...              ...              ...   ...   
2         0.61                  0.52             1.06             7.70  0.64   
2         0.75                  0.43             1.41             7.30  0.70   
2         0.69                  0.43             1.35            10.20  0.59   
2         0.68                  0.53             1.46             9.30  0.60   
2         0.76                  0.56             1.35             9.20  0.61   

    od280/od315_of_diluted_wines  proline  
0                           3.92   1065.0  
0                           3.40   1050.0  
0                           3.17   1185.0  
0                           3.45   1480.0  
0                           2.93    735.0  
..                           ...      ...  
2                           1.74    740.0  
2                           1.56    750.0  
2                           1.56    835.0  
2                           1.62    840.0  
2                           1.60    560.0  

[178 rows x 13 columns]

In [17]:
y= df.target
y

0    0
0    0
0    0
0    0
0    0
    ..
2    2
2    2
2    2
2    2
2    2
Name: target, Length: 178, dtype: int32

In [18]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2)

In [19]:
len(X_train)

142

In [20]:
gb = GaussianNB()
mb = MultinomialNB()
bb = BernoulliNB()

In [21]:
gb.fit(X_train,y_train)

GaussianNB()

In [22]:
gb.predict(X_test)

array([1, 2, 2, 0, 1, 1, 0, 2, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 2, 0, 2, 0,
       1, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0])

In [23]:
y_test.head()


1    1
2    2
2    2
0    0
1    1
Name: target, dtype: int32

In [24]:
gb.score(X_test,y_test)

1.0

In [25]:
gb.predict([[14,4,3,22,98,1.5,0.8,0.5,1.2,7.8,0.6,2,628]])

array([2])

In [26]:
mb.fit(X_train,y_train)

MultinomialNB()

In [27]:
mb.predict(X_test)

array([1, 1, 2, 0, 1, 2, 0, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0])

In [28]:
mb.score(X_test,y_test)

0.8055555555555556

In [29]:
mb.predict([[14,4,3,22,98,1.5,0.8,0.5,1.2,7.8,0.6,2,628]])

array([2])

In [30]:
bb.fit(X_train,y_train)

BernoulliNB()

In [31]:
bb.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
bb.score(X_test,y_test)

0.4166666666666667